Repository juniorUsca/get-things-done, pull requests merged in 2021-06, with the labels that each got.

#65 fix(microservicio de Inbox): Bug en la URL de eliminación de inbox
  microservice/apiNode/package-lock.json
  microservice/apiNode/routes/inbox.js
Labels: enhancement

#93 Issue03 feat(NextJs): Verificación por email con firebase
  app/.env.local
  app/package-lock.json
  app/package.json
  app/src/pages/firebase.js
  app/src/pages/index.js
Labels: enhancement

#100 feat: instalacion de Eslint para comenzar con un Codigo Limpio
  MicroserviceImbox/ApiNodeJS/.eslintrc.cjs
  MicroserviceImbox/ApiNodeJS/package-lock.json
  MicroserviceImbox/ApiNodeJS/package.json
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/CreateImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/DeleteAllImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/DeleteImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/GetImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/ShowAllImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/UpdateImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/controller.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/infraestructure/MongoImboxRepository.js
  MicroserviceImbox/ApiNodeJS/src/config.js
  MicroserviceImbox/ApiNodeJS/src/index.js
  MicroserviceImbox/ApiNodeJS/src/lib/mongo.js
  MicroserviceImbox/ApiNodeJS/src/routes/inbox.js
  MicroserviceImbox/ApiNodeJS/src/utils/middlewares/errorHandlers.js
  MicroserviceImbox/ApiNodeJS/src/utils/middlewares/notFoundHandler.js
Labels: enhancement, good first issue

#91 feat(microservicio con MongoDB): Se creo el microservicio de Mongodb …
  microservice/apiNode/README.md
  microservice/apiNode/config.js
  microservice/apiNode/index.js
  microservice/apiNode/mongodb/README.md
  microservice/apiNode/mongodb/index.js
  microservice/apiNode/mongodb/network.js
  microservice/apiNode/mongodb/response/response.js
  microservice/apiNode/mongodb/store/mongodb.js
  microservice/apiNode/package-lock.json
  microservice/apiNode/package.json
  microservice/apiNode/postman/Proyecto final.postman_collection.json
  microservice/apiNode/remote/remote-mongodb.js
  microservice/apiNode/remote/remote.js
  microservice/apiNode/routes/components/todo/controller.js
  microservice/apiNode/routes/components/todo/index.js
  microservice/apiNode/routes/components/todo/network.js
Labels: enhancement

#62 feat(Validation): Firebase User Login and Validation finished
  MobileApp/iOS/getThingsDone/.gitignore
  MobileApp/iOS/getThingsDone/Podfile
  MobileApp/iOS/getThingsDone/Podfile.lock
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.pbxproj
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MobileApp/iOS/getThingsDone/getThingsDone.xcworkspace/contents.xcworkspacedata
  MobileApp/iOS/getThingsDone/getThingsDone.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MobileApp/iOS/getThingsDone/getThingsDone/AppDelegate.swift
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/AppIcon.appiconset/Contents.json
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/Contents.json
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/user.imageset/Contents.json
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/user.imageset/man.png
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/LaunchScreen.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/Main.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/DesignableView.swift
  MobileApp/iOS/getThingsDone/getThingsDone/GoogleService-Info.plist
  MobileApp/iOS/getThingsDone/getThingsDone/HomeViewController.swift
  MobileApp/iOS/getThingsDone/getThingsDone/Info.plist
  MobileApp/iOS/getThingsDone/getThingsDone/LogInViewController.swift
  MobileApp/iOS/getThingsDone/getThingsDone/SceneDelegate.swift
Labels: enhancement, good first issue

#97 fix(microservicio de Inbox): Bug en la URL de edición de inbox
  microservice/apiNode/routes/inbox.js
Labels: enhancement

#102 #issue56 feat(NextJs): Interfaz de calendario para NextJs
  app/src/pages/index.js
  app/src/pages/main.js
Labels: enhancement

#112 #110 feat(Flutter): Se mejoro el diseño del Login
  MobileApp/Flutter/getthingsdone/README.md
  MobileApp/Flutter/getthingsdone/assets/icons/cita.svg
  MobileApp/Flutter/getthingsdone/lib/Views/Login.dart
  MobileApp/Flutter/getthingsdone/lib/Views/SigIn.dart
  MobileApp/Flutter/getthingsdone/lib/Views/background_page.dart
  MobileApp/Flutter/getthingsdone/lib/main.dart
  MobileApp/Flutter/getthingsdone/pubspec.lock
  MobileApp/Flutter/getthingsdone/pubspec.yaml
Labels: documentation, enhancement

#119 Crear pefil de usuario de la aplicación de flutter #118
  MobileApp/Flutter/getthingsdone/lib/Models/apisample.dart
  MobileApp/Flutter/getthingsdone/lib/Views/profile_Page.dart
  MobileApp/Flutter/getthingsdone/lib/main.dart
  MobileApp/Flutter/getthingsdone/lib/provider/google_sign_in.dart
  MobileApp/Flutter/getthingsdone/lib/widgets/logged_in_widget.dart
  MobileApp/Flutter/getthingsdone/pubspec.lock
  MobileApp/Flutter/getthingsdone/pubspec.yaml
  docs/main.md
Labels: documentation, enhancement

#135 fix(inbox): validations when user is invalid
  microservice/api_Firebase/functions/src/routes/inbox.js
Labels: enhancement

#151 #150 feat(Flutter): Se añadió la navegación en el proyecto Flutter
  MobileApp/Flutter/getthingsdone/lib/Views/Login.dart
  MobileApp/Flutter/getthingsdone/lib/Views/SigIn.dart
  MobileApp/Flutter/getthingsdone/lib/main.dart
Labels: enhancement

#152 #68 feat(flutter):Login con Google
  MobileApp/Flutter/getthingsdone/android/app/build.gradle
  MobileApp/Flutter/getthingsdone/android/app/google-services.json
  MobileApp/Flutter/getthingsdone/android/app/src/main/AndroidManifest.xml
  MobileApp/Flutter/getthingsdone/android/build.gradle
  MobileApp/Flutter/getthingsdone/lib/Controllers/Controller.dart
  MobileApp/Flutter/getthingsdone/lib/Views/Login.dart
  MobileApp/Flutter/getthingsdone/pubspec.lock
  MobileApp/Flutter/getthingsdone/pubspec.yaml
Labels: enhancement, good first issue

#155 #69 feat(flutter): Diseño HomePage Fluter
  MobileApp/Flutter/getthingsdone/lib/Views/home_view/background.dart
  MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
  MobileApp/Flutter/getthingsdone/lib/Views/login_view/Login.dart
Labels: enhancement

#156 #71 feat(flutter): Barra Latera
  MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
  MobileApp/Flutter/getthingsdone/lib/Views/lateral_menu_view/background_lateral.dart
  MobileApp/Flutter/getthingsdone/lib/Views/lateral_menu_view/menu_lateral.dart
Labels: enhancement

#157 #77 feat(flutter): Calendario y Anadir notas
  MobileApp/Flutter/getthingsdone/lib/Views/calendar_view/calendario_page.dart
  MobileApp/Flutter/getthingsdone/lib/Views/calendar_view/event.dart
  MobileApp/Flutter/getthingsdone/lib/Views/lateral_menu_view/menu_lateral.dart
  MobileApp/Flutter/getthingsdone/pubspec.lock
  MobileApp/Flutter/getthingsdone/pubspec.yaml
Labels: enhancement, good first issue

#158 #70 feat(flutter): Diseño Formulario Nueva Tarea
  MobileApp/Flutter/getthingsdone/lib/Views/form_view/form_page.dart
  MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
  MobileApp/Flutter/getthingsdone/lib/Views/login_view/background_page.dart
Labels: enhancement, good first issue

#166 test(microservicio de Inbox): Aplicación de tests al microservicio Node-Inbox
  microservice/apiNode/.babelrc
  microservice/apiNode/index.js
  microservice/apiNode/package-lock.json
  microservice/apiNode/package.json
  microservice/apiNode/tests/api.test.js
Labels: enhancement

#175 #173 feat(flutter): Validaciones para el LogIn
  MobileApp/Flutter/getthingsdone/README.md
  MobileApp/Flutter/getthingsdone/lib/Views/login_view/Login.dart
  MobileApp/Flutter/getthingsdone/lib/bloc/login_bloc.dart
  MobileApp/Flutter/getthingsdone/lib/bloc/provider.dart
  MobileApp/Flutter/getthingsdone/lib/bloc/validators.dart
  MobileApp/Flutter/getthingsdone/lib/main.dart
Labels: enhancement, good first issue

#179 #172 feat(flutter): Informacion para el Login con Google
  MobileApp/Flutter/getthingsdone/README.md
Labels: documentation, enhancement

#178 Diseño de la pagina de Bienvenida
  app/src/pages/welcome.js
Labels: enhancement

#188 issue#59 feat(NextJs): Prototipo interfaz de cambio de contraseña pa…
  MobileApp/Flutter/getthingsdone/pubspec.lock
  ui/Prototipo de Interfaz para cambio de contraseña en NextJs.PNG
  ui/Prototipo de Interfaz para cambio de contraseña en NextJs.fig
Labels: documentation

#189 [FIX] Script de la base de datos gtd #132
  documentation/gtd.sql
  microservice/apiJava/pom.xml
  microservice/apiJava/src/main/resources/application.properties
  microservice/apiJava/src/main/resources/static/index.html
Labels: enhancement

#192 test(microservicio Node - MongoDB): Aplicación de tests al microservicio Node-MongoDB
  microservice/apiNode/config.js
  microservice/apiNode/mongodb/index.js
  microservice/apiNode/mongodb/network.js
  microservice/apiNode/mongodb/store/mongodb.js
  microservice/apiNode/package.json
  microservice/apiNode/tests/mongo.test.js
Labels: enhancement

#195 [FIX] CREDENCIALES DEL SERVICIO RDS EN AWS #194
  documentation/credenciales_aws_rds.md
  microservice/apiJava/README.md
  microservice/apiJava/pom.xml
  microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/ICalendar.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/IInbox.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/IIncubadura.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/INextActions.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/ITicklerFile.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/dao/IUsers.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Calendar.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Inbox.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Incubadura.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/NextActions.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/TicklerFile.java
  microservice/apiJava/src/main/java/com/gtd/apijava/back/modelo/Users.java
  microservice/apiJava/src/main/resources/application.properties
Labels: enhancement

#200 issue#193 feat(Creacion de la interfaz del Dashboard - menus)
  app/package-lock.json
  app/package.json
  app/postcss.config.js
  app/src/components/Layout/Navbar/Navbar.js
  app/src/components/Layout/Sidebar/Sidebar.js
  app/src/components/Layout/layout.js
  app/src/pages/calendar.js
  app/src/pages/inbox.js
  app/src/styles/globals.css
  app/tailwind.config.js
Labels: enhancement

#211 Creación de otra Propuesta diagrama MER para la Base de datos del Proyecto
  documentation/Comandos de la Base de datos MYSQL.txt
  documentation/DIAGRAMA MER GTD.png
Labels: enhancement

#214 Implementacion de Menu Adaptativo NextJS
  app/package-lock.json
  app/package.json
  app/src/pages/SnapBar.js
  app/src/pages/welcome.js
Labels: enhancement

#213 Issue #210 feat(Crud Inbox con MongoDB)
  microservice/apiNode/example.env
  microservice/apiNode/index.js
  microservice/apiNode/mongodb/network.js
  microservice/apiNode/mongodb/store/mongodb.js
  microservice/apiNode/remote/remote.js
  microservice/apiNode/response/response.js
  microservice/apiNode/routes/components/inbox/controller.js
  microservice/apiNode/routes/components/inbox/index.js
  microservice/apiNode/routes/components/inbox/network.js
  microservice/apiNode/routes/components/todo/controller.js
  microservice/apiNode/routes/components/todo/network.js
Labels: enhancement

#215 Sistema de Login y Registro en el microservicio de NodeJS
  microservice/apiNode/index.js
  microservice/apiNode/package-lock.json
  microservice/apiNode/package.json
  microservice/apiNode/routes/components/inbox/network.js
  microservice/apiNode/routes/components/user/controller.js
  microservice/apiNode/routes/components/user/index.js
  microservice/apiNode/routes/components/user/network.js
Labels: enhancement

#216 Barra lateral de nuevo proyecto de flutter con animaciones
  MobileApp/Login-Animated/dribbbledanimation/img/barra.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/barra2.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/chicharron.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/fondo-comida.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/hambur.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/helado-chocolate.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/palomitas-maiz.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/pollo.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/promosion.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/ramen.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/sniker.jpg
  MobileApp/Login-Animated/dribbbledanimation/img/torta.jpg
  MobileApp/Login-Animated/dribbbledanimation/lib/Components/comida.dart
  MobileApp/Login-Animated/dribbbledanimation/lib/Components/nosotros.dart
  MobileApp/Login-Animated/dribbbledanimation/lib/Screens/Login/index.dart
  MobileApp/Login-Animated/dribbbledanimation/pubspec.yaml
Labels: enhancement

#220 Issue #209 feat(Autenticación en el backend con JWT)
  microservice/apiNode/README.md
  microservice/apiNode/auth/index.js
  microservice/apiNode/config.js
  microservice/apiNode/package-lock.json
  microservice/apiNode/package.json
  microservice/apiNode/postman/Proyecto final.postman_collection.json
  microservice/apiNode/routes/components/inbox/network.js
  microservice/apiNode/routes/components/inbox/secure.js
  microservice/apiNode/routes/components/user/controller.js
  microservice/apiNode/routes/components/user/network.js
  microservice/apiNode/routes/components/user/secure.js
Labels: enhancement

#221 Prototipo de login y registro para android(Figma)
  ui/PrototipoAndroid(inicio,sign up, sign in).fig
  ui/PrototipoAndroid(inicio,sign up, sign in).png
Labels: enhancement

#222 Se agrego consumo de http get
  MobileApp/Flutter/getthingsdone/lib/Controllers/todo_controller.dart
  MobileApp/Flutter/getthingsdone/lib/Models/todo.dart
  MobileApp/Flutter/getthingsdone/lib/Views/todo_view/home_screen.dart
  MobileApp/Flutter/getthingsdone/lib/repository/repository.dart
  MobileApp/Flutter/getthingsdone/lib/repository/todo_repository.dart
  MobileApp/Flutter/getthingsdone/pubspec.lock
  MobileApp/Flutter/getthingsdone/pubspec.yaml
Labels: enhancement

#223 Se agrego http put y patch
  MobileApp/Flutter/getthingsdone/lib/Controllers/todo_controller.dart
  MobileApp/Flutter/getthingsdone/lib/Views/todo_view/home_screen.dart
  MobileApp/Flutter/getthingsdone/lib/repository/repository.dart
  MobileApp/Flutter/getthingsdone/lib/repository/todo_repository.dart
Labels: enhancement

#224 Se agrego http delete
  MobileApp/Flutter/getthingsdone/lib/Controllers/todo_controller.dart
  MobileApp/Flutter/getthingsdone/lib/Views/todo_view/home_screen.dart
  MobileApp/Flutter/getthingsdone/lib/repository/repository.dart
  MobileApp/Flutter/getthingsdone/lib/repository/todo_repository.dart
Labels: enhancement

#225 se agrego http post
  MobileApp/Flutter/getthingsdone/lib/Controllers/todo_controller.dart
  MobileApp/Flutter/getthingsdone/lib/Views/todo_view/home_screen.dart
  MobileApp/Flutter/getthingsdone/lib/repository/repository.dart
  MobileApp/Flutter/getthingsdone/lib/repository/todo_repository.dart
Labels: enhancement

#227 fix(MicroserviceImbox): modificando la estructura de la tabla IMBOX
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/CreateImbox.js
  MicroserviceImbox/ApiNodeJS/src/components/imbox/application/UpdateImbox.js
Labels: enhancement

#231 Arreglando fallo al editar más de 1 vez una tarea
  app/src/pages/inbox.js
Labels: upgrade or update

#226 Implementacion Funcionalidad al Snap Bar vista Welcome NextJS
  app/src/pages/SnapBar.js
Labels: enhancement

#232 feat(MicroservicioCalendary): Implementacion del microservice con DDD
  MicroserviceImbox/microservice_calendary/.env.example
  MicroserviceImbox/microservice_calendary/.eslintrc.cjs
  MicroserviceImbox/microservice_calendary/package-lock.json
  MicroserviceImbox/microservice_calendary/package.json
  MicroserviceImbox/microservice_calendary/src/components/calendary/application/CreateCalendary.js
  MicroserviceImbox/microservice_calendary/src/components/calendary/application/DeleteCalendary.js
  MicroserviceImbox/microservice_calendary/src/components/calendary/application/GetCalendary.js
  MicroserviceImbox/microservice_calendary/src/components/calendary/application/ShowAllCalendary.js
  MicroserviceImbox/microservice_calendary/src/components/calendary/application/UpdateCalendary.js
  MicroserviceImbox/microservice_calendary/src/components/calendary/controller.js
  MicroserviceImbox/microservice_calendary/src/components/calendary/infraestructure/MongoCalendaryRepository.js
  MicroserviceImbox/microservice_calendary/src/config.js
  MicroserviceImbox/microservice_calendary/src/index.js
  MicroserviceImbox/microservice_calendary/src/lib/mongo.js
  MicroserviceImbox/microservice_calendary/src/routes/calendary.js
  MicroserviceImbox/microservice_calendary/src/utils/middlewares/errorHandlers.js
  MicroserviceImbox/microservice_calendary/src/utils/middlewares/notFoundHandler.js
Labels: enhancement

#234 feat(microservicioEncubadora): Creacion microservice Incubadora_tareas
  MicroserviceImbox/microservice_encubadora/.env.example
  MicroserviceImbox/microservice_encubadora/.eslintrc.cjs
  MicroserviceImbox/microservice_encubadora/package-lock.json
  MicroserviceImbox/microservice_encubadora/package.json
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/application/CreateIncubadora.js
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/application/DeleteIncubadora.js
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/application/GetIncubadora.js
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/application/ShowAllIncubadora.js
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/application/UpdateIncubadora.js
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/controller.js
  MicroserviceImbox/microservice_encubadora/src/components/incubadora/infraestructure/MongoIncubadoraRepository.js
  MicroserviceImbox/microservice_encubadora/src/config.js
  MicroserviceImbox/microservice_encubadora/src/index.js
  MicroserviceImbox/microservice_encubadora/src/lib/mongo.js
  MicroserviceImbox/microservice_encubadora/src/routes/incubadora.js
  MicroserviceImbox/microservice_encubadora/src/utils/middlewares/errorHandlers.js
  MicroserviceImbox/microservice_encubadora/src/utils/middlewares/notFoundHandler.js
  MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/CreateCalendary.js
  MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/DeleteCalendary.js
  MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/GetCalendary.js
  MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/ShowAllCalendary.js
  MicroserviceImbox/microservice_tickler_file/src/components/calendary/application/UpdateCalendary.js
  MicroserviceImbox/microservice_tickler_file/src/components/calendary/controller.js
Labels: enhancement

#235 Diseño de Card Anotation
  app/src/pages/anotation.js
Labels: enhancement

#244 Implementacion de Vista envio de Correos para reporte de problemas o Dudas (NextJS)
  app/cypress.json
  app/cypress/fixtures/example.json
  app/cypress/fixtures/profile.json
  app/cypress/fixtures/users.json
  app/cypress/integration/calendar.spec.js
  app/cypress/integration/home.spec.js
  app/cypress/integration/home2.spec.js
  app/cypress/integration/report.spec.js
  app/cypress/integration/welcome.spec.js
  app/cypress/plugins/index.js
  app/cypress/screenshots/All Integration Specs/my-image.png
  app/cypress/support/commands.js
  app/cypress/support/index.js
  app/package-lock.json
  app/package.json
  app/src/pages/SnapBar.js
  app/src/pages/components/LoginComponents/Login.js
  app/src/pages/components/RegisterComponents/Register.js
  app/src/pages/components/SocialContainer.js
  app/src/pages/report.js
Labels: enhancement

#246 Page 404 Modification
  app/src/pages/404.js
  app/src/styles/globals.css
Labels: enhancement

#247 Animacion con Rive para Login Flutter
  ui/flutter animacion/login_animate.mp4
  ui/flutter animacion/login_animate.riv
Labels: enhancement

#248 Implementacion Prototipo Calendar Page Web App
  ui/WebApp/Calendar Page/GTD-Calendar.fig
  ui/WebApp/Calendar Page/GTD-Calendar.pdf
Labels: documentation, enhancement

#256 Documentacion Firebase Google
  app/README.md
Labels: documentation

#253 Implementacion Login Screen - Manejo de Errores e Interfaz y Prototipo Login ReactNative Mobile App
  ReactNativeApp/get-things-done/App.js
  ReactNativeApp/get-things-done/assets/img/logo-gtd.png
  ReactNativeApp/get-things-done/assets/img/logo.png
  ReactNativeApp/get-things-done/assets/img/profile.jpg
  ReactNativeApp/get-things-done/components/CredentialsContext.js
  ReactNativeApp/get-things-done/components/KeyboardAvoidingWrapper.js
  ReactNativeApp/get-things-done/components/styles.js
  ReactNativeApp/get-things-done/navigators/RootStack.js
  ReactNativeApp/get-things-done/package-lock.json
  ReactNativeApp/get-things-done/screens/Login.js
  ui/ReactNativeApp/Login/Login - React Native.fig
  ui/ReactNativeApp/Login/Login - React Native.pdf
Labels: enhancement, good first issue

#258 Documentacion Firebase Facebook
  app/README.md
Labels: documentation

#257 Implementacion Prototipo User Profile realizado con Figma
  ui/WebApp/ProfilePage/GTD - Profile.fig
  ui/WebApp/ProfilePage/GTD - Profile.pdf
Labels: documentation, enhancement

#261 fix(Bug iOS): Bug fixes finished by assigning files to those who did …
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.pbxproj
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/Main.storyboard
Labels: enhancement

#262 Subiendo Diagrama de Procesos del Proyecto desarrollado en Bizagi Modeler
  documentation/Get-Things-Done.bpm
Labels: enhancement

#263 Listado de todo Inbox en Aplicación IOS
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.pbxproj
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/Main.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/Modelos/Inbox.swift
  MobileApp/iOS/getThingsDone/getThingsDone/New Group/DesignableView.swift
  MobileApp/iOS/getThingsDone/getThingsDone/Utils/InboxViewController.swift
  MobileApp/iOS/getThingsDone/getThingsDone/ViewControllers/HomeViewController.swift
Labels: enhancement

#266 Cambio de uso de APi a uso de Core Data, para la persistencia de datos
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.pbxproj
  MobileApp/iOS/getThingsDone/getThingsDone/AppDelegate.swift
  MobileApp/iOS/getThingsDone/getThingsDone/Info.plist
  MobileApp/iOS/getThingsDone/getThingsDone/Model.xcdatamodeld/Model.xcdatamodel/contents
  MobileApp/iOS/getThingsDone/getThingsDone/Modelos/Inbox.swift
  MobileApp/iOS/getThingsDone/getThingsDone/Utils/InboxViewController.swift
Labels: enhancement

#270 App IOS: Agregar Inbox
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.pbxproj
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/Main.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/Model.xcdatamodeld/Model.xcdatamodel/contents
  MobileApp/iOS/getThingsDone/getThingsDone/Utils/InboxViewController.swift
  MobileApp/iOS/getThingsDone/getThingsDone/ViewControllers/AñadirInboxViewController.swift
Labels: enhancement

#277 feat(ValidationLogin): Login form validation finished
  app/src/pages/components/LoginComponents/Login.js
  app/src/pages/components/RegisterComponents/Register.js
  app/src/pages/components/validation.js
  app/src/pages/components/validationRegister.js
  app/src/pages/utils/expressions.js
Labels: enhancement

#278 vista configuracion
  app/src/pages/configuration.js
Labels: documentation

#281 Implementacion logo opcional (modificacion)
  ui/Resources/img/logo opcional.jpg
Labels: documentation

#283 Ordenamiento de lista y Editing style
  MobileApp/iOS/getThingsDone/getThingsDone/AppDelegate.swift
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/Aplicaciones-organizar-vida-1280x720.imageset/Aplicaciones-organizar-vida-1280x720.png
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/Aplicaciones-organizar-vida-1280x720.imageset/Contents.json
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/LaunchScreen.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/Main.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/Utils/InboxViewController.swift
Labels: enhancement

#284 implementacion de vista testimonios
  app/src/pages/testimonials.js
Labels: enhancement

#285 snapbar y estilos en la vista testimonios
  app/src/pages/testimonials.js
Labels: enhancement

#286 feat(LaunchScreenAnimation): Finished home screen animation in Swfit …
  MobileApp/iOS/getThingsDone/getThingsDone.xcodeproj/project.pbxproj
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/logo.imageset/Contents.json
  MobileApp/iOS/getThingsDone/getThingsDone/Assets.xcassets/logo.imageset/logotipo-triangular.png
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/LaunchScreen.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/Base.lproj/Main.storyboard
  MobileApp/iOS/getThingsDone/getThingsDone/ViewControllers/ViewController.swift
Labels: enhancement

#289 Documentacion Firebase GitHub
  app/README.md
Labels: documentation

#288 Correccion de error en la interfas Login
  MobileApp/Flutter/getthingsdone/README.md
  MobileApp/Flutter/getthingsdone/android/app/build.gradle
  MobileApp/Flutter/getthingsdone/android/app/src/main/AndroidManifest.xml
  MobileApp/Flutter/getthingsdone/android/app/src/main/res/values/string.xml
  MobileApp/Flutter/getthingsdone/assets/icons/gethings.svg
  MobileApp/Flutter/getthingsdone/ios/Runner/AppDelegate.swift
  MobileApp/Flutter/getthingsdone/ios/Runner/Info.plist
  MobileApp/Flutter/getthingsdone/lib/Views/home_view/home_page.dart
  MobileApp/Flutter/getthingsdone/lib/Views/login_view/Login.dart
  MobileApp/Flutter/getthingsdone/lib/Views/login_view/background_page.dart
  MobileApp/Flutter/getthingsdone/lib/main.dart
  MobileApp/Flutter/getthingsdone/pubspec.lock
  MobileApp/Flutter/getthingsdone/pubspec.yaml
Labels: enhancement
